"""
Page 4 — Risk & Recommendations: alert table, recommendation cards, risk drill-down.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import streamlit as st
import pandas as pd
import numpy as np

from src.data_loader import load_operational_data, MOIL_MINES
from src.production_model import train_production_model, predict_production_bulk
from src.risk_engine import generate_recommendations, generate_mine_summary, THRESHOLDS
from src.visualization import risk_donut, PALETTE, RISK_COLOURS

st.set_page_config(page_title="Risk & Recommendations — MOIL AI", page_icon="⚠️", layout="wide")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Orbitron:wght@700&display=swap');
html,body,[class*="css"]{font-family:'Inter',sans-serif;}
.main{background:#0a0e1a;}
[data-testid="stSidebar"]{background:linear-gradient(180deg,#0d1b2a 0%,#1a2744 100%);border-right:1px solid #1e3a5f;}
[data-testid="stSidebar"] *{color:#e2e8f0 !important;}
.risk-critical,.risk-high,.risk-medium,.risk-low{padding:.25rem .7rem;border-radius:6px;font-size:.75rem;font-weight:700;text-transform:uppercase;}
.risk-critical{background:rgba(239,68,68,.15);border:1px solid rgba(239,68,68,.4);color:#f87171;}
.risk-high{background:rgba(251,146,60,.15);border:1px solid rgba(251,146,60,.4);color:#fb923c;}
.risk-medium{background:rgba(250,204,21,.15);border:1px solid rgba(250,204,21,.4);color:#facc15;}
.risk-low{background:rgba(74,222,128,.15);border:1px solid rgba(74,222,128,.4);color:#4ade80;}
.rec-card-critical{background:rgba(239,68,68,.06);border:1px solid rgba(239,68,68,.3);border-left:3px solid #f87171;border-radius:8px;padding:1rem;margin:.5rem 0;}
.rec-card-high{background:rgba(251,146,60,.06);border:1px solid rgba(251,146,60,.3);border-left:3px solid #fb923c;border-radius:8px;padding:1rem;margin:.5rem 0;}
.rec-card-medium{background:rgba(250,204,21,.06);border:1px solid rgba(250,204,21,.3);border-left:3px solid #facc15;border-radius:8px;padding:1rem;margin:.5rem 0;}
.rec-card-low{background:rgba(74,222,128,.06);border:1px solid rgba(74,222,128,.3);border-left:3px solid #4ade80;border-radius:8px;padding:1rem;margin:.5rem 0;}
.info-box{background:rgba(56,189,248,.08);border:1px solid rgba(56,189,248,.25);border-left:3px solid #38bdf8;border-radius:8px;padding:.75rem 1rem;font-size:.85rem;color:#94a3b8;margin:.75rem 0;}
.section-header{font-size:1rem;font-weight:600;color:#e2e8f0;margin-bottom:.75rem;}
#MainMenu{visibility:hidden;}footer{visibility:hidden;}[data-testid="stToolbar"]{visibility:hidden;}
header[data-testid="stHeader"]{background:transparent !important;visibility:visible !important;display:block !important;z-index:99999 !important;}
[data-testid="collapsedControl"],[data-testid="collapsedControl"] button,[data-testid="stSidebarCollapseButton"],header button{visibility:visible !important;display:inline-flex !important;opacity:1 !important;color:#38bdf8 !important;}
[data-testid="collapsedControl"]{background:rgba(13,27,42,.95) !important;border:1px solid #1e3a5f !important;border-radius:8px !important;box-shadow:0 4px 12px rgba(0,0,0,.5) !important;}
[data-testid="collapsedControl"]:hover{border-color:#38bdf8 !important;box-shadow:0 0 10px rgba(56,189,248,.5) !important;}
</style>
""", unsafe_allow_html=True)

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("---")
    st.markdown("**Filters**")
    risk_filter = st.multiselect(
        "Risk Levels", ["CRITICAL","HIGH","MEDIUM","LOW"],
        default=["CRITICAL","HIGH","MEDIUM"],
    )
    mine_filter = st.multiselect("Mines", list(MOIL_MINES.keys()), default=list(MOIL_MINES.keys()))
    date_range  = st.date_input(
        "Analysis Period",
        value=(pd.Timestamp("2024-10-01"), pd.Timestamp("2024-12-31")),
    )

# ── Title ──────────────────────────────────────────────────────────────────────
st.markdown("""
<div style="margin-bottom:1rem;">
    <h1 style="font-family:'Orbitron',monospace;font-size:1.6rem;font-weight:700;
    background:linear-gradient(135deg,#f87171,#fb923c);-webkit-background-clip:text;
    -webkit-text-fill-color:transparent;background-clip:text;margin:0;">
    ⚠️ Risk Intelligence &amp; Recommendations
    </h1>
    <p style="color:#94a3b8;margin:.2rem 0 0;">
    Rule-based recommendation engine — transparent, explainable, no LLM dependency
    </p>
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class="info-box">
🔍 <strong>Engine Design:</strong> Recommendations are generated by a transparent rule-based system 
using configurable thresholds. Each recommendation links: Risk Factor → Evidence → Action. 
No LLM — fully auditable logic.
</div>
""", unsafe_allow_html=True)

# ── Load & train ───────────────────────────────────────────────────────────────
with st.spinner("Loading data…"):
    ops_df = load_operational_data()
    reg, clf, metrics, fi = train_production_model(ops_df)
    ops_pred = predict_production_bulk(reg, clf, ops_df)

# ── Filter ─────────────────────────────────────────────────────────────────────
filt = ops_pred.copy()
if isinstance(date_range, (list, tuple)) and len(date_range) == 2:
    filt = filt[
        (filt["date"] >= pd.Timestamp(date_range[0])) &
        (filt["date"] <= pd.Timestamp(date_range[1]))
    ]
if mine_filter:
    filt = filt[filt["mine"].isin(mine_filter)]
if risk_filter:
    filt = filt[filt["risk_label"].isin(risk_filter)]

# ── KPIs ───────────────────────────────────────────────────────────────────────
crit = (filt["risk_label"] == "CRITICAL").sum()
high = (filt["risk_label"] == "HIGH").sum()
med  = (filt["risk_label"] == "MEDIUM").sum()
low  = (filt["risk_label"] == "LOW").sum()
total_sf = filt["shortfall_tpd"].sum()

k1, k2, k3, k4, k5 = st.columns(5)
for col, (val, lab, col_hex) in zip(
    [k1, k2, k3, k4, k5],
    [
        (crit, "🔴 Critical Days",  "#f87171"),
        (high, "🟠 High-Risk Days", "#fb923c"),
        (med,  "🟡 Medium Days",    "#facc15"),
        (low,  "🟢 Low-Risk Days",  "#4ade80"),
        (f"{total_sf:,.0f} t", "Total Shortfall (Period)", "#818cf8"),
    ]
):
    with col:
        st.markdown(f"""
        <div style="background:linear-gradient(135deg,#0d1b2a,#1a2744);border:1px solid #1e3a5f;
        border-radius:12px;padding:1.1rem;text-align:center;">
            <div style="font-size:1.7rem;font-weight:700;color:{col_hex};">{val}</div>
            <div style="color:#94a3b8;font-size:.72rem;margin-top:.25rem;text-transform:uppercase;">{lab}</div>
        </div>""", unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# ── Mine Alert Table ───────────────────────────────────────────────────────────
st.markdown('<div class="section-header">🚨 Mine Risk Alert Table</div>', unsafe_allow_html=True)

mine_summary = generate_mine_summary(filt, filt)
if mine_summary.empty:
    mine_summary = generate_mine_summary(ops_pred, ops_pred)

if not mine_summary.empty:
    for _, row in mine_summary.iterrows():
        risk = row.get("Risk Level", "LOW")
        if risk not in risk_filter:
            continue
        badge_class = f"risk-{risk.lower()}"
        card_class  = f"rec-card-{risk.lower()}"
        sf_pct = row["Shortfall %"]
        sf_col = RISK_COLOURS.get(risk, "#fff")

        st.markdown(f"""
        <div class="{card_class}">
            <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:.5rem;">
                <div>
                    <span style="color:#e2e8f0;font-weight:700;font-size:.95rem;">⛏️ {row['Mine']}</span>
                    <span style="color:#94a3b8;font-size:.8rem;margin-left:.75rem;">
                    Shortfall: {row['Expected Shortfall (t)']:.0f} t 
                    (<span style="color:{sf_col};font-weight:600;">{sf_pct:.1f}%</span>)
                    </span>
                </div>
                <span class="{badge_class}">{risk}</span>
            </div>
            <div style="color:#94a3b8;font-size:.82rem;margin-bottom:.4rem;">
                <strong style="color:#e2e8f0;">Main Cause:</strong> {row['Main Cause']}
            </div>
            <div style="color:#94a3b8;font-size:.82rem;">
                <strong style="color:#e2e8f0;">Action:</strong> {row['Recommended Action']}
            </div>
        </div>
        """, unsafe_allow_html=True)

# ── Interactive Deep-Dive ──────────────────────────────────────────────────────
st.markdown("---")
st.markdown("### 🔎 Detailed Recommendation Drill-Down")

col_sel, col_recs = st.columns([1, 2], gap="medium")

with col_sel:
    sel_mine = st.selectbox("Select Mine", list(MOIL_MINES.keys()), key="riskmine")
    st.markdown('<div class="section-header">⚙️ Operational Inputs</div>', unsafe_allow_html=True)

    planned_tpd    = st.number_input("Planned t/day", 100, 5000,
                                     int(MOIL_MINES[sel_mine]["capacity_tpd"] * 0.9), step=50,
                                     key="r_planned")
    predicted_tpd  = st.number_input("Predicted t/day", 0, 5000,
                                     int(MOIL_MINES[sel_mine]["capacity_tpd"] * 0.78), step=50,
                                     key="r_pred")
    downtime_hrs   = st.slider("Downtime hrs/day", 0.0, 12.0, 4.5, 0.5, key="r_dt")
    blasting_delay = st.slider("Blasting Delay hrs", 0.0, 8.0, 3.5, 0.5, key="r_bd")
    rainfall_mm    = st.slider("Rainfall mm", 0, 120, 55, key="r_rain")
    equip_avail    = st.slider("Equipment Availability %", 30, 100, 68, key="r_ea")
    maintenance    = st.selectbox("Maintenance Event", [0, 1],
                                   format_func=lambda x: "Yes" if x else "No", key="r_maint")

    shortfall_pct = max((planned_tpd - predicted_tpd) / planned_tpd * 100, 0)

with col_recs:
    recs = generate_recommendations(
        mine=sel_mine,
        planned_tpd=planned_tpd,
        predicted_tpd=predicted_tpd,
        shortfall_pct=shortfall_pct,
        downtime_hrs=downtime_hrs,
        blast_delay_hrs=blasting_delay,
        rainfall_mm=rainfall_mm,
        equip_avail_pct=equip_avail,
        maintenance_event=maintenance,
    )

    st.markdown(f'<div class="section-header">📋 Recommendations for {sel_mine}</div>',
                unsafe_allow_html=True)

    for rec in recs:
        sev  = rec["severity"]
        card_class  = f"rec-card-{sev.lower()}"
        badge_class = f"risk-{sev.lower()}"

        st.markdown(f"""
        <div class="{card_class}">
            <div style="display:flex;align-items:center;gap:.5rem;margin-bottom:.5rem;">
                <span style="font-size:1.2rem;">{rec['icon']}</span>
                <span style="color:#e2e8f0;font-weight:700;font-size:.9rem;">{rec['factor']}</span>
                <span class="{badge_class}">{sev}</span>
            </div>
            <div style="display:flex;gap:.5rem;align-items:flex-start;margin-bottom:.4rem;">
                <span style="color:#94a3b8;font-size:.75rem;min-width:80px;font-weight:600;">EVIDENCE</span>
                <span style="color:#94a3b8;font-size:.82rem;">{rec['evidence']}</span>
            </div>
            <div style="display:flex;gap:.5rem;align-items:flex-start;">
                <span style="color:#e2e8f0;font-size:.75rem;min-width:80px;font-weight:600;">ACTION</span>
                <span style="color:#e2e8f0;font-size:.85rem;">{rec['recommendation']}</span>
            </div>
        </div>
        """, unsafe_allow_html=True)

# ── Risk donut + Threshold reference ──────────────────────────────────────────
st.markdown("---")
col_donut, col_thresholds = st.columns([2, 1], gap="medium")

with col_donut:
    st.markdown('<div class="section-header">🍩 Risk Distribution</div>', unsafe_allow_html=True)
    st.plotly_chart(risk_donut(filt), use_container_width=True, key="risk_donut_page")

with col_thresholds:
    st.markdown('<div class="section-header">📏 Rule Engine Thresholds</div>', unsafe_allow_html=True)
    th_data = [
        ("Equipment Downtime HIGH", f"≥ {THRESHOLDS['downtime_high']} hrs/day"),
        ("Equipment Downtime CRITICAL", f"≥ {THRESHOLDS['downtime_critical']} hrs/day"),
        ("Blasting Delay HIGH", f"≥ {THRESHOLDS['blast_delay_high']} hrs"),
        ("Blasting Delay CRITICAL", f"≥ {THRESHOLDS['blast_delay_critical']} hrs"),
        ("Rainfall MODERATE", f"≥ {THRESHOLDS['rainfall_moderate']} mm/day"),
        ("Rainfall HIGH", f"≥ {THRESHOLDS['rainfall_high']} mm/day"),
        ("Equipment Avail LOW", f"< {THRESHOLDS['equip_avail_low']}%"),
        ("Equipment Avail CRITICAL", f"< {THRESHOLDS['equip_avail_critical']}%"),
        ("Shortfall MEDIUM", f"≥ {THRESHOLDS['shortfall_medium']}%"),
        ("Shortfall HIGH", f"≥ {THRESHOLDS['shortfall_high']}%"),
        ("Shortfall CRITICAL", f"≥ {THRESHOLDS['shortfall_critical']}%"),
    ]
    for k, v in th_data:
        st.markdown(f"""
        <div style="display:flex;justify-content:space-between;font-size:.78rem;
        padding:.3rem 0;border-bottom:1px solid #1e3a5f;color:#94a3b8;">
            <span>{k}</span><span style="color:#e2e8f0;font-weight:600;">{v}</span>
        </div>
        """, unsafe_allow_html=True)

st.markdown("---")
st.caption(
    "⚠️ Prototype operational dataset — synthetic (not official MOIL records). "
    "Rule thresholds are configurable and should be calibrated with real MOIL operational data."
)
